name: Create release

on:
  push:
    branches:
      - main
      - ci/upload-release # temporary

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4.1.6
      - name: Build
        run: ./build.bat      
      - name: Create release
        uses: softprops/action-gh-release@v2.0.5
        with:
          name: Old Games Steam Launchers - ${{ github.sha }}
          prerelease: {{ github.ref != 'refs/heads/main' }}
          fail_on_unmatched_files: true
          generate_release_notes: true
          make_latest: {{ github.ref == 'refs/heads/main' }}
          files: |
            *.exe
            README.md
